language: node_js
node_js:
  - '0.10'
branches:
  only:
    - master
    - development
before_install:
  - npm install -g bower
  - npm install -g gulp
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-oasp' ]; then cd .. && eval "mv $currentfolder generator-oasp" && cd generator-oasp; fi
